[package]
name = "main-bevy"
version = "0.1.0"
publish = false
authors = ["PIGSquad Rustaceans"]
edition = "2024"

[[bin]]
name = "inventory_jam"
path = "src/main.rs"

[lints.clippy]
expect_used = "deny"
panic = "deny"
unwrap_used = "deny"

[package.metadata.dist]
dist = true
include = ["assets", "../public"]
auto-includes = false  # Skip auto-bundling README.md.
windows-archive = ".zip"
unix-archive = ".zip"
installers = []
default-features = false
features = ["client", "gui", "server", "netcode", "udp", "webtransport"]

[features]
dev = ["core/dev", "bevy/dynamic_linking", "dep:bevy-inspector-egui"]
default = ["client", "gui", "server", "netcode", "udp", "webtransport", "dev"]
client = ["core/client", "lightyear/client"]
gui = ["core/gui"]
server = ["core/server", "lightyear/client", "lightyear/server"]
netcode = ["core/netcode"]
udp = ["core/udp"]
link_conditioner = ["core/link_conditioner"]
webtransport = ["core/webtransport"]

[dependencies]
core = { path = "../core", default-features = false }
bevy = { workspace = true }
lightyear = { workspace = true }
bevy-inspector-egui = { workspace = true, optional = true }

[build-dependencies]
embed-resource = { workspace = true }

[package.metadata.bevy_cli.web]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
default-features = false
features = ["client", "gui", "netcode", "webtransport"]
