[target.wasm32-unknown-unknown]
rustflags = [
    '--cfg', 'getrandom_backend="wasm_js"',
    '--cfg', 'web_sys_unstable_apis',
]
runner = "wasm-server-runner"

# Faster linking on Windows (https://bevy.org/learn/quick-start/getting-started/setup/)
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[build]
# it is a good idea to specify your target here, to avoid losing incremental compilation when compiling to wasm
# target = "aarch64-apple-darwin"
rustflags = ["--cfg", "web_sys_unstable_apis"]
