# Bevy fast-compile settings:
# https://bevy.org/learn/quick-start/getting-started/setup/
# https://github.com/bevyengine/bevy/blob/main/.cargo/config_fast_builds.toml

[target.x86_64-pc-windows-msvc]
# Faster linker than the MSVC default. Requires:
#   cargo install -f cargo-binutils
#   rustup component add llvm-tools
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg", "getrandom_backend=\"wasm_js\"",
    "--cfg", "web_sys_unstable_apis",
]
runner = "wasm-server-runner"
